#!/bin/bash

# Define command-line arguments
NAMESPACE=$1
RESOURCE_TYPE=$2

__plugin_help() {
  echo 'kubeplugin usage:'
  echo
  echo 'kubectl kubeplugin [<namespace>] [<resource_type>]'
  echo
  echo '  where <resource_type> is one of available values:'
  echo '    node          Display resource (CPU/memory) usage of nodes'
  echo '    pod           Display resource (CPU/memory) usage of pods'
}

# Retrieve resource usage statistics from Kubernetes
__plugin_start() {

  if [[ $RESOURCE_TYPE == "" ]]; then RESOURCE_TYPE="pod"; fi
  if [[ $NAMESPACE == "" ]]; then NAMESPACE="default"; fi

  if [[ $RESOURCE_TYPE != "node" && $RESOURCE_TYPE != "pod" ]]
  then
    __plugin_help
    exit 0
  fi

  echo -e "Resource, Namespace, Name, CPU, Memory"
  kubectl top $RESOURCE_TYPE -n $NAMESPACE | tail -n +2 | while read line
  do
    # Extract CPU and memory usage from the output
    NAME=$(echo $line | awk '{print $1}')
    CPU=$(echo $line | awk '{print $2}')
    MEMORY=$(echo $line | awk '{print $3}')
    if [[ $RESOURCE_TYPE == "node" ]]; then MEMORY=$(echo $line | awk '{print $4}'); fi

    # Output the statistics to the console
    # "Resource, Namespace, Name, CPU, Memory"
    echo -e "$RESOURCE_TYPE, $NAMESPACE, $NAME, $CPU, $MEMORY"
  done
}

if [[ "$1" == "--help" ]]
then
  __plugin_help
  exit 0
fi

if [[ "$1" == "-v" || "$1" == "--version" ]]
then
  echo "kubeplugin version v1.0.0"
  exit 0
fi

__plugin_start
