---
apiVersion: v1
kind: Pod
metadata:
  name: bbrc-pod
spec:
  containers:
  - name: bbrc
    image: nickp6/bbrc:v1.0.0
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: data
      mountPath: /data
    livenessProbe:
      httpGet:
        path: /
        port: 8080
    readinessProbe:
      httpGet:
        path: /ready
        port: 8080
  volumes:
  - name: data
    hostPath:
      path: /var/lib/bbrc
